allow_url_fopen = On
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
short_open_tag = On
memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 300
date.timezone = Asia/Jakarta
auto_prepend_file = /var/www/html/ioncube_alias.php
